package com.test.derby;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

public class TestDerby {
	public static void main(String[] args) {
		try {
			Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();// 加载驱动
			Properties props = new Properties();
			props.put("user", "test");
			props.put("password", "test");

			Connection conn = DriverManager.getConnection(
					"jdbc:derby:helloDB1;create=true", props);// 连接数据库
			Statement st = conn.createStatement();
			// st.execute("create table USER_INFO (ID INT NOT NULL,NAME VARCHAR(10) NOT NULL)");//
			// 建表
			// st.executeUpdate("insert into USER_INFO(ID,NAME) values (1,'hermit')");//
			// 插入数据
			st.executeUpdate("insert into USER_INFO(ID, NAME) values (5, '黎明1')");// 插入数据
			ResultSet rs = st.executeQuery("select * from USER_INFO");// 读取刚插入的数据
			while (rs.next()) {
				int id = rs.getInt(1);
				String name = rs.getString(2);
				System.out.println("ID=" + id);
				System.out.println("NAME=" + name);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void createTable() {
		try {
			Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
			// 加载驱动
			Properties props = new Properties();
			props.put("user", "test");
			props.put("password", "test");

			Connection conn = DriverManager.getConnection(
					"jdbc:derby:liuyan;create=true", props);// 连接数据库
			Statement st = conn.createStatement();
			String createSql = "create table USER_INFO " +
					"(ID INT generated by default as identity," +
					"NAME VARCHAR(10) NOT NULL)," +
					"pass varchar(20) not null";
			st.execute(createSql);
			// 建表
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
